tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DEVELOPER_ROLE
      database: SANDBOX_SWAYAM
      schema: _DEV_DLH_TEST_MART
      warehouse: SWAYAM_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DEVELOPER_ROLE
      database: SANDBOX_SWAYAM
      schema: DLH_TEST_MART
      warehouse: SWAYAM_WH